version: '3'
services:

  # ------------------------------- WFE --------------------------------
  web:
    container_name: web
    image: "python:3"
    entrypoint: "tail -f /dev/null"
    working_dir: /app
    ports:
     - "8000:8000"
    volumes:
      - ./web/:/app/
    networks:
      - dev

  # ------------------------------- DATABASE --------------------------------
  postgresdb:
    container_name: postgresdb
    image: "postgres:13"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chainlink_kovan
    ports:
     - "5432:5432"
    networks:
      - dev

  # ------------------------------- CHAINLINK NODE --------------------------------

  chainlink:
    container_name: chainlink
    image: "smartcontract/chainlink:latest"
    entrypoint: chainlink
    command: local n -p /chainlink/password -a /chainlink/api
    environment:
      - ROOT=/chainlink
      - LOG_LEVEL=debug
      - ETH_CHAIN_ID=42
      - MIN_OUTGOING_CONFIRMATIONS=2
      - LINK_CONTRACT_ADDRESS=0xa36085F69e2889c224210F603D836748e7dC0088
      - CHAINLINK_TLS_PORT=0
      - SECURE_COOKIES=false
      - GAS_UPDATER_ENABLED=true
      - ALLOW_ORIGINS=*
      - ETH_URL=wss://kovan.infura.io/ws/v3/8cefcaa06dad492f8e954e9a1d9b16d9
      - DATABASE_URL=postgresql://postgres:postgres@postgresdb.dev:5432/chainlink_kovan?sslmode=disable

    volumes:
      - ./data/chainlink-kovan/:/chainlink

    ports:
     - "6688:6688"
    depends_on: [ postgresdb ]
    networks:
      - dev




networks:
  dev:
    external:
      name: dev
