version: '3'
services:

  # ------------------------------- WFE --------------------------------
  web:
    container_name: web
    image: "python:3"
    entrypoint: "sh entrypoint.sh"
    command: python site.py
    environment:
      - REDIS_HOST=redisdb.dev
      - "OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}"
      - "OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}"
    working_dir: /app
    ports:
     - "8000:8000"
    depends_on: [ redisdb ]
    volumes:
      - ./web/:/app/
    networks:
      - dev

  # ------------------------------- DATABASE --------------------------------
  postgresdb:
    container_name: postgresdb
    image: "postgres:13"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chainlink_kovan
    ports:
     - "5432:5432"
    networks:
      - dev

  redisdb:
    container_name: redisdb
    image: "redis"
    ports:
     - "6379:6379"
    networks:
      - dev
  # ------------------------------- CHAINLINK NODE --------------------------------

  chainlink:
    container_name: chainlink
    image: "smartcontract/chainlink:latest"
    entrypoint: chainlink
    command: local n -p /chainlink/password -a /chainlink/api
    environment:
      - ROOT=/chainlink
      - LOG_LEVEL=debug
      - ETH_CHAIN_ID=42
      - MIN_OUTGOING_CONFIRMATIONS=2
      - LINK_CONTRACT_ADDRESS=0xa36085F69e2889c224210F603D836748e7dC0088
      - MINIMUM_CONTRACT_PAYMENT=100000000000000000
      - CHAINLINK_TLS_PORT=0
      - SECURE_COOKIES=false
      - GAS_UPDATER_ENABLED=true
      - ALLOW_ORIGINS=*
      - ETH_URL=wss://kovan.infura.io/ws/v3/8cefcaa06dad492f8e954e9a1d9b16d9
      - DATABASE_URL=postgresql://postgres:postgres@postgresdb.dev:5432/chainlink_kovan?sslmode=disable

    volumes:
      - ./data/chainlink-kovan/:/chainlink

    ports:
     - "6688:6688"
    depends_on: [ postgresdb ]
    networks:
      - dev


  # ------------------------------- External_adapter --------------------------------
  external_adapter:
    container_name: external_adapter
    image: "python:3"

    entrypoint: "sh entrypoint.sh"
    command: python external_adapter.py
    environment:
      - REDIS_HOST=redisdb.dev

    working_dir: /app
    ports:
     - "8001:8000"
    depends_on: [ redisdb ]
    volumes:
      - ./external_adapter/:/app/
    networks:
      - dev


  # ------------------------------- WFE --------------------------------
  smart_contracts:
    container_name: smart_contracts
    image: "python:3"
    entrypoint: "tail -f /dev/null"
    working_dir: /app
    environment:
      - WEB3_INFURA_PROJECT_ID=8cefcaa06dad492f8e954e9a1d9b16d9
    volumes:
      - ./smart_contracts/:/app/
    networks:
      - dev


networks:
  dev:
    external:
      name: dev
